# -*- coding: utf-8 -*-
#
# MONK Automated Testing Framework
#
# Copyright (C) 2013 DResearch Fahrzeugelektronik GmbH
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version
# 2 of the License, or (at your option) any later version.
#

language: python

python:
 - "2.7"

install:
 - "python setup.py sdist"
 - "pip install dist/monk_tf-0.1.1.tar.gz"

script:
 - "python test/test_all.py"

before_install:
 - "sudo apt-get install python2.7 python2.7-dev libssh2-1 libssh2-1-dev"
 - "sudo apt-get install python-pip"
